apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-app-deployment
spec:
  selector:
    matchLabels:
      app: pos-app
  replicas: 2 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: pos-app
    spec:
      containers:
      - name: nginx
        image: sivaseturaj/pos-app-by-react:1.1.0
        ports:
        - containerPort: 80
        livenessProbe:  #probes section
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pos-app-service
spec:
  #type: NodePort
  selector:
    app: pos-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
